TC_NAME = syno-$(TC_ARCH)

TC_ARCH = 88f6281
TC_VERS = 4.2
TC_FIRMWARE = 4.2-3259

TC_DIST_NAME = gcc421_glibc25_88f6281-GPL.tgz

TC_EXT = tgz
TC_DIST_SITE = http://sourceforge.net/projects/dsgpl/files/DSM%204.2%20Tool%20Chains/Marvell%2088F628x%20Linux%202.6.32

TC_BASE_DIR = arm-none-linux-gnueabi
TC_PREFIX = arm-none-linux-gnueabi
TC_TARGET = arm-none-linux-gnueabi

TC_CFLAGS = -I$(WORK_DIR)/$(TC_BASE_DIR)/$(TC_BASE_DIR)/libc/usr/include
TC_CPPFLAGS = -I$(WORK_DIR)/$(TC_BASE_DIR)/$(TC_BASE_DIR)/libc/usr/include
TC_CXXFLAGS = -I$(WORK_DIR)/$(TC_BASE_DIR)/$(TC_BASE_DIR)/libc/usr/include
TC_LDFLAGS = -L$(WORK_DIR)/$(TC_BASE_DIR)/$(TC_BASE_DIR)/libc/usr/lib

include ../../mk/spksrc.tc.mk
